@hostname = localhost:8080

## ping
GET http://{{hostname}}/ping

### openid
GET http://{{hostname}}/openid
    ?js_code=053Vq01w3g315Z2v523w3sdHsx1Vq01I

### schedule GET
GET http://{{hostname}}/schedule/123
